name: ProShield
main: com.proshield.ProShield
version: 1.0.0
api-version: 1.19
author: YourName
description: A plot protection and management system with customizable radius, buffers, and protection rules.

commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command> [reload|claim|check]
    aliases: [ps]

permissions:
  proshield.reload:
    description: Allows reloading the ProShield configuration.
    default: op

  proshield.claim:
    description: Allows claiming a plot of land.
    default: true

  proshield.check:
    description: Allows players to check if they’re inside their own plot.
    default: true
