name: ProShield
main: com.proshield.ProShield
version: 1.0.0
api-version: 1.19
author: snazzyatons
description: A flexible plot protection plugin with configurable building rules.

commands:
  proshield:
    description: Main ProShield command.
    usage: /<command> [reload|claim|check]
    aliases: [ps]
    permission: proshield.use

permissions:
  proshield.use:
    description: Allows access to base ProShield commands.
    default: true

  proshield.reload:
    description: Allows reloading the ProShield configuration.
    default: op

  proshield.claim:
    description: Allows players to claim plots.
    default: true

  proshield.check:
    description: Allows players to check their plot info.
    default: true
