name: ProShield
main: com.proshield.ProShield
version: 1.0.0
api-version: 1.16
author: snazzyatoms
description: >
  ProShield is the ultimate land protection plugin for Spigot/Paper servers.
  It combines plot protection, GUI-based management, economy hooks, backups,
  and Discord integration into one simple package.

commands:
  proshield:
    description: Main ProShield command
    usage: /<command> [args]
    aliases: [ps]
    permission: proshield.use

permissions:
  proshield.use:
    description: Allows basic use of ProShield commands
    default: true
  proshield.reload:
    description: Allows reloading of ProShield configuration
    default: op
