name: ProShield
main: com.proshield.ProShield
version: 1.0.0
author: YourName
api-version: 1.16
description: >
  ProShield is a flexible land protection plugin with plot claiming,
  expansion, admin tools, backups, economy integration, and Discord support.

commands:
  proshield:
    description: Main command for ProShield
    usage: /proshield <claim|check|reload>
    aliases: [pshield]

permissions:
  proshield.use:
    description: Allows use of /proshield claim and check
    default: true
  proshield.reload:
    description: Allows reloading of the ProShield configuration
    default: op
  proshield.admin:
    description: Grants access to admin-only features
    default: op
