name: Release (Signed Artifacts)

on:
  push:
    tags:
      - 'v*'          # e.g. v1.1.8

permissions:
  contents: write    # allow creating GitHub Releases

jobs:
  release:
    name: Build & Sign on Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Temurin Java ${{ matrix.java }} + GPG + OSSRH
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
          server-id: ossrh                                  # <servers><server><id>ossrh</id>...
          server-username: OSSRH_USERNAME                   # from secrets
          server-password: OSSRH_PASSWORD                   # from secrets
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}   # ASCII-armored key
          gpg-passphrase:  ${{ secrets.GPG_PASSPHRASE }}

      - name: Build & Sign (GPG)
        run: |
          mvn -B -Psign -DskipTests verify

      - name: Collect Artifacts
        run: |
          mkdir -p release
          cp target/*.jar release/ || true
          cp target/*.asc release/ || true

      - name: Upload build artifacts (per Java)
        uses: actions/upload-artifact@v4
        with:
          name: proshield-${{ github.ref_name }}-java${{ matrix.java }}
          path: release/*

  publish:
    name: Publish GitHub Release (attach all artifacts)
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate release notes (CHANGELOG.md fallback)
        id: notes
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          if [ -f CHANGELOG.md ]; then
            awk 'BEGIN{p=0}/^## /{if(p)exit; if($2==ENVIRON["TAG"])p=1} p' CHANGELOG.md > body.md
          fi
          if [ ! -s body.md ]; then
            echo "Release ${TAG}" > body.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.notes.outputs.tag }}
          name: ProShield ${{ steps.notes.outputs.tag }}
          body_path: body.md
          files: |
            dist/**/*
