name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.2
api-version: 1.16
author: SnazzyAtoms
description: A lightweight plot protection plugin for Minecraft servers.

commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command> <claim|unclaim>
    aliases: [ps]
