name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
api-version: 1.18
author: SnazzyAtoms
description: ProShield - Advanced plot and protection management plugin

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> [reload]
    aliases: [pshield, ps]
    permission: proshield.use

permissions:
  proshield.use:
    description: Allows use of the /proshield command
    default: true
  proshield.admin:
    description: Allows bypassing protections and administrative features
    default: op
