name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.5
api-version: 1.20
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield

description: >
  ProShield is a lightweight yet powerful land & plot protection plugin 
  for Spigot and Paper servers. Secure claims, manage trust & roles, 
  repel mobs, protect items, and provide intuitive GUIs for players and admins.

commands:
  proshield:
    description: Main ProShield command (opens GUI, help, or Admin Tools)
    usage: /<command> [help|admin|reload|debug|bypass]
    aliases: [ps, shield]
    permission: proshield.player.access

permissions:
  # --- Player Core Access ---
  proshield.player.access:
    description: Allows players to access all standard ProShield GUI features
    default: true

  proshield.unlimited:
    description: Bypass claim limits (admin-level)
    default: op

  # --- Admin Tools ---
  proshield.admin:
    description: Grants access to all admin tools, including reload/debug/bypass/admin GUI
    default: op

  proshield.admin.expansions:
    description: Allows approval/denial of claim expansions via Admin GUI
    default: op

  proshield.admin.worldcontrols:
    description: Access to world-level protections and overrides in Admin Tools
    default: op
