name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.4
api-version: 1.18
author: snazzyatoms
description: Land and plot protection plugin with GUI management and admin tools.
softdepend: [Vault, LuckPerms]

commands:
  proshield:
    description: Main ProShield command
    usage: |
      /proshield
      /proshield claim
      /proshield unclaim
      /proshield info
      /proshield compass
      /proshield trust <player> [role]
      /proshield untrust <player>
      /proshield trusted
      /proshield bypass <on|off|toggle>
      /proshield preview [seconds]
      /proshield transfer <player>
      /proshield purgeexpired <days> [dryrun]
      /proshield debug <on|off|toggle>
      /proshield reload

permissions:
  proshield.use:
    description: Use ProShield commands and GUI
    default: true

  proshield.compass:
    description: Receive/use the ProShield compass
    default: op

  proshield.admin:
    description: Admin tools (bypass, transfer, purge, preview)
    default: op

  proshield.bypass:
    description: Toggle protection bypass
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit
    default: op

  proshield.admin.tp:
    description: Teleport to claims from admin menu
    default: op

  proshield.admin.reload:
    description: /proshield reload
    default: op

  proshield.admin.expired.purge:
    description: Purge expired claims
    default: op

  proshield.admin.debug:
    description: Toggle debug logging
    default: op

  proshield.admin.keydrops:
    description: Allow toggling claim item-keep/pickup rules
    default: op

  proshield.admin.gui:
    description: Open the ProShield Admin GUI
    default: op

  proshield.admin.spawnoverride:
    description: Allows claiming inside the protected spawn radius
    default: op
