name: ProShield
main: com.proshield.ProShield
version: 1.0.0
author: snazzyatoms
description: >
  Advanced plot protection and management system with customizable radius,
  buffer zones, and protection rules.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> [reload|claim|check|help]
    aliases: [ps]

permissions:
  proshield.reload:
    description: Allows reloading the ProShield configuration.
    default: op

  proshield.claim:
    description: Allows claiming a plot of land.
    default: true

  proshield.check:
    description: Allows players to check if they are inside their own plot.
    default: true

  proshield.help:
    description: Allows access to the ProShield help command.
    default: true
