name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.5
api-version: 1.20
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield
description: >
  ProShield is a lightweight yet powerful land & plot protection plugin 
  for Spigot and Paper servers. Secure claims, manage trust & roles, 
  repel mobs, protect items, and provide intuitive GUIs for players and admins.

commands:
  proshield:
    description: Root ProShield command (help, claims, admin tools)
    usage: /<command> [help|claim|unclaim|info|compass|reload|debug|bypass|admin]
    aliases: [ps, shield, claim, unclaim, info, compass, roles, trust, untrust, transfer]
    permission: proshield.player.access

permissions:
  # --- Player Core ---
  proshield.player.access:
    description: Full access to all standard player features 
      (GUI, claim, unclaim, info, flags, roles, trust/untrust, transfer, compass)
    default: true

  proshield.unlimited:
    description: Ignore max-claims limit
    default: op

  # --- Admin Core ---
  proshield.admin:
    description: Access all Admin Tools (reload, debug, bypass, admin GUI)
    default: op

  # --- Senior Admin (High Control) ---
  proshield.admin.expansions:
    description: Approve/Deny expansion requests in Admin Tools GUI
    default: op

  proshield.admin.worldcontrols:
    description: Manage per-world controls in Admin Tools GUI
    default: op

  # --- Protection / Flags (NEW) ---
  proshield.flags.safezone:
    description: Control safezone flag (repels/blocks mobs, despawns inside)
    default: op

  proshield.flags.explosions:
    description: Control explosions flag
    default: op

  proshield.flags.fire:
    description: Control fire spread / ignite flags
    default: op

  proshield.flags.buckets:
    description: Control bucket usage flags
    default: op

  proshield.flags.entities:
    description: Control entity protection flags (vehicles, frames, pets, passives)
    default: op
