name: ProShield
version: 1.1.6
main: com.snazzyatoms.proshield.ProShield
api-version: 1.19
author: SnazzyAtoms
description: A powerful region and claim protection system with admin GUI and compass tool.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> <subcommand>
    aliases: [ps]
    subcommands:
      compass:
        description: Gives the ProShield Admin Compass
        usage: /proshield compass
      create:
        description: Create a new claim at your current position
        usage: /proshield create
      info:
        description: Show claim info for your current location
        usage: /proshield info
      remove:
        description: Remove your claim at the current position
        usage: /proshield remove

permissions:
  proshield.*:
    description: Gives access to all ProShield commands and features
    default: op

  proshield.compass:
    description: Allows access to the ProShield Admin Compass
    default: op

  proshield.create:
    description: Allows creating claims
    default: true

  proshield.info:
    description: Allows viewing claim info
    default: true

  proshield.remove:
    description: Allows removing claims
    default: op
