name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.6
api-version: 1.20
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield

description: >
  ProShield is a lightweight yet powerful land & plot protection plugin 
  for Spigot and Paper servers. Secure claims, manage trust & roles, 
  repel mobs, protect items, and provide intuitive GUIs for players and admins.

commands:
  proshield:
    description: Main ProShield command (opens GUI, help, or Admin Tools)
    usage: |
      /<command> [help|compass|admin|reload|debug|bypass]
      Tip: All player features are GUI-driven. Commands are not required.
    aliases: [ps, shield]
    permission: proshield.player.access

permissions:
  # --- Player Core Access ---
  proshield.player.access:
    description: Allows players to open the GUI and use all standard ProShield features
    default: true

  proshield.unlimited:
    description: Bypass claim limits (admin-level)
    default: op

  # --- Admin Tools (Granular Access) ---
  proshield.admin:
    description: Grants access to the Admin Tools GUI and core commands (reload/debug/bypass)
    default: op

  proshield.admin.expansions:
    description: Allows approval/denial of claim expansions via Admin Tools GUI
    default: op

  proshield.admin.worldcontrols:
    description: Access to world-level protections and overrides in Admin Tools GUI
    default: op

  # --- Specific Toggles (optional granularity) ---
  proshield.admin.reload:
    description: Use /proshield reload or reload via Admin Tools GUI
    default: op

  proshield.admin.debug:
    description: Toggle debug logging (/proshield debug)
    default: op

  proshield.admin.bypass:
    description: Toggle bypass protection (/proshield bypass or via GUI)
    default: op

  proshield.admin.keepitems:
    description: Toggle claim item-drop protection (GUI toggle if enabled)
    default: op

  proshield.admin.spawn:
    description: Bypass spawn-guard restrictions (when enabled in config)
    default: op

  proshield.admin.mobrepel:
    description: Toggle mob repel borders in Admin Tools GUI
    default: op

  # --- Quality-of-Life Permissions ---
  proshield.compass:
    description: Allow receiving/using the ProShield compass manually (/proshield compass)
    default: op
