name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
api-version: 1.17
author: SnazzyAtoms
description: A flexible plot protection and management system for Minecraft servers.

commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command> [reload|info|help]
    aliases: [pshield, shield]

permissions:
  proshield.admin:
    description: Full access to ProShield admin features.
    default: op
  proshield.use:
    description: Basic ProShield user commands.
    default: true
