name: ProShield
version: 1.1.3
main: com.proshield.managers.ProShield
api-version: 1.20
author: snazzyatoms
description: Ultimate land protection plugin for Spigot/Paper servers.
commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command>
