name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.0
api-version: 1.18
author: snazzyatoms
description: Land and plot protection plugin with GUI management, roles, expansion and QoL tools.

softdepend:
  - Vault
  - LuckPerms
  - PlaceholderAPI

commands:
  proshield:
    description: Main ProShield command
    usage: |
      /proshield
      /proshield claim
      /proshield unclaim
      /proshield info
      /proshield compass
      /proshield trust <player>
      /proshield untrust <player>
      /proshield trusted
      /proshield bypass <on|off|toggle>
      /proshield reload
      # 1.2 placeholders (coming in 1.2.x GUI/commands)
      /proshield expand <north|south|east|west> <amount>
      /proshield home [#]
      /proshield message <enter|leave> <text>
      /proshield role <add|remove|set> <player> <member|manager>

permissions:
  proshield.use:
    description: Allows players to use ProShield commands and GUI
    default: true

  proshield.admin:
    description: Admin features (admin compass, force unclaim, tp, bypass, expiry review)
    default: op

  proshield.compass:
    description: Allows a player to receive and use the ProShield compass
    default: op

  proshield.bypass:
    description: Allows toggling protection bypass
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit
    default: false

  proshield.admin.tp:
    description: Allows teleporting to other players’ claims from the admin menu
    default: op

  proshield.admin.reload:
    description: Allows /proshield reload (config + internal caches)
    default: op

  proshield.admin.expired.purge:
    description: Allows purging expired claims
    default: op
