name: ProShield
version: 1.0.6
main: com.snazzyatoms.proshield.ProShield
api-version: 1.19
author: snazzyatoms
description: A lightweight protection plugin for Minecraft servers.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command>
    aliases: [pshield, shield]

permissions:
  proshield.use:
    description: Allows use of ProShield commands
    default: true
  proshield.admin:
    description: Allows access to all ProShield admin commands
    default: op

softdepend:
  - DiscordSRV
