name: ProShield
main: com.yourname.proshield.ProShield
version: 1.0.6
api-version: 1.16
author: YourName
description: A flexible plot protection and management system with GUI and Discord integration support.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> [subcommand]

permissions:
  proshield.admin:
    description: Allows access to all ProShield admin features
    default: op
  proshield.use:
    description: Allows players to use ProShield plot features
    default: true

softdepend:
  - DiscordSRV
