name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.5
api-version: 1.18
author: SnazzyAtoms
description: Lightweight land & plot protection plugin for Spigot and Paper. Easy claims, trust roles, GUI menus, and admin tools.

commands:
  proshield:
    description: Main ProShield command
    usage: /<command> [args]
    aliases: [ps]

permissions:
  proshield.use:
    description: Use ProShield commands and GUI
    default: true
  proshield.compass:
    description: Receive and use the ProShield compass
    default: op
  proshield.admin:
    description: Access ProShield admin tools
    default: op
  proshield.bypass:
    description: Toggle admin bypass
    default: op
  proshield.unlimited:
    description: Ignore max claims limit
    default: op
  proshield.admin.tp:
    description: Teleport to claims from admin menu
    default: op
  proshield.admin.reload:
    description: Reload ProShield configs
    default: op
  proshield.admin.expired.purge:
    description: Purge expired claims
    default: op
  proshield.admin.keepdrops:
    description: Toggle item-keep inside claims
    default: op
  proshield.admin.transfer:
    description: Transfer claim ownership
    default: op
  proshield.admin.debug:
    description: Toggle debug logging
    default: op

softdepend:
  - Vault
  - PlaceholderAPI
