name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.6.1
api-version: 1.20
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield

description: >
  ProShield is a lightweight yet powerful land & plot protection plugin 
  for Spigot and Paper servers. Secure claims, manage trust & roles, 
  repel mobs, protect items, and provide intuitive GUIs for players and admins.
  Includes multilingual starter packs (20+ languages) with easy config toggle.  
  To change language: edit `settings.language` in config.yml (e.g. "fr", "pl", "de") 
  and run `/proshield reload`. ProShield will extract the correct messages_xx.yml 
  file into the plugin folder automatically and use it immediately (English fallback included).

commands:
  proshield:
    description: Main ProShield command (open GUI, get compass, or run admin tools)
    usage: |
      /<command> help      - Show help menu
      /<command> compass   - Get or open the ProShield Compass
      /<command> admin     - Open Admin Tools GUI (requires permission)
      /<command> reload    - Reload plugin configs
      /<command> debug     - Toggle debug mode
      /<command> bypass    - Toggle admin bypass mode
    aliases: [ps, shield]

permissions:
  # --- Player Umbrella ---
  proshield.player.*:
    description: Grants all standard player-level permissions
    default: true
    children:
      proshield.player.access: true
      proshield.player.claim: true
      proshield.compass: true
      proshield.transfer: true
      proshield.preview: true

  # --- Admin Umbrella ---
  proshield.admin.*:
    description: Grants all admin-level permissions (includes expansions/world controls)
    default: op
    children:
      proshield.admin: true
      proshield.admin.expansions: true
      proshield.admin.worldcontrols: true
      proshield.admin.reload: true
      proshield.admin.debug: true
      proshield.admin.bypass: true
      proshield.admin.keepitems: true
      proshield.admin.spawn: true
      proshield.admin.mobrepel: true
      proshield.unlimited: true

  # --- Player Core Access ---
  proshield.player.access:
    description: Allows players to open the GUI and use all standard ProShield features
    default: true

  proshield.player.claim:
    description: Allows players to create and manage their own claims
    default: true

  proshield.unlimited:
    description: Bypass claim limits (admin-level)
    default: op

  # --- Admin Tools (Granular Access) ---
  proshield.admin:
    description: Grants access to the Admin Tools GUI and core commands (reload/debug/bypass)
    default: op

  proshield.admin.expansions:
    description: Allows approval/denial of claim expansions via Admin Tools GUI
    default: op

  proshield.admin.worldcontrols:
    description: Access to world-level protections and overrides in Admin Tools GUI
    default: op

  # --- Specific Toggles (optional granularity) ---
  proshield.admin.reload:
    description: Use /proshield reload or reload via Admin Tools GUI
    default: op

  proshield.admin.debug:
    description: Toggle debug logging (/proshield debug)
    default: op

  proshield.admin.bypass:
    description: Toggle bypass protection (/proshield bypass or via GUI)
    default: op

  proshield.admin.keepitems:
    description: Toggle claim item-drop protection (GUI toggle if enabled)
    default: op

  proshield.admin.spawn:
    description: Bypass spawn-guard restrictions (when enabled in config)
    default: op

  proshield.admin.mobrepel:
    description: Toggle mob repel borders in Admin Tools GUI
    default: op

  # --- Quality-of-Life Permissions ---
  proshield.compass:
    description: Allow receiving/using the ProShield compass manually (/proshield compass)
    default: true

  proshield.transfer:
    description: Allow transferring claim ownership (/proshield transfer)
    default: true

  proshield.preview:
    description: Allow using claim preview particles (/proshield preview)
    default: true
