name: ProShield
version: 1.1.1
main: com.snazzyatoms.proshield.ProShield
api-version: 1.16
author: snazzyatoms
description: A simple plot protection plugin for Minecraft servers.

commands:
  proshield:
    description: Main ProShield command
    usage: /<command> <protect|unprotect|check>
