name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.8
api-version: '1.18'
authors: [ snazzyatoms ]
website: https://github.com/snazzyatoms/ProShield
description: All-in-one land & plot protection for Paper/Spigot.

commands:
  proshield:
    description: ProShield main command
    usage: /proshield [claim|unclaim|info|trust|untrust|trusted|show|bypass|admin ...]
    aliases: [ps, psd]

permissions:
  proshield.use:
    description: Use ProShield commands and GUI.
    default: true

  proshield.admin:
    description: Admin features (compass, admin subcommands).
    default: op

  proshield.bypass:
    description: Build/Interact bypass in all claims.
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit.
    default: op
