name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
api-version: 1.17
author: SnazzyAtoms
description: A powerful claim protection and management plugin with GUI support.

commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command> <subcommand>
    aliases: [ps]
    permission: proshield.use
    subcommands:
      compass:
        description: Gives you the ProShield Compass (admins only).
        usage: /proshield compass
        permission: proshield.compass

permissions:
  proshield.*:
    description: Grants access to all ProShield commands and features.
    default: op
    children:
      proshield.use: true
      proshield.compass: true

  proshield.use:
    description: Allows basic usage of ProShield commands.
    default: true

  proshield.compass:
    description: Allows receiving and using the ProShield Compass.
    default: op
