name: ProShield
main: com.proshield.ProShield
version: 1.0.0
api-version: 1.20
author: YourName
description: Advanced plot protection & management plugin with GUI, economy hooks, and admin tools.

commands:
  proshield:
    description: Base command for ProShield
    usage: /<command> [subcommand]
    aliases: [ps, shield]

permissions:
  proshield.use:
    description: Allows basic use of ProShield commands
    default: true

  proshield.admin:
    description: Grants access to all admin commands and GUI features
    default: op

  proshield.debug:
    description: Allows enabling debug mode
    default: op
