# path: src/main/resources/plugin.yml
name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.2
api-version: 1.18
author: snazzyatoms
description: Land and plot protection plugin with GUI management and admin tools.

softdepend:
  - Vault
  - LuckPerms
  - EssentialsX

commands:
  proshield:
    description: Main ProShield command
    usage: |
      /proshield
      /proshield claim
      /proshield unclaim
      /proshield info
      /proshield trust <player>
      /proshield untrust <player>
      /proshield trusted
      /proshield compass
      /proshield bypass <on|off|toggle>
      /proshield reload
      /proshield purgeexpired

permissions:
  proshield.use:
    description: Use ProShield commands and GUI
    default: true

  proshield.admin:
    description: Access admin tools (compass, bypass, force unclaim, teleport, purge)
    default: op

  proshield.compass:
    description: Receive/use the ProShield compass
    default: op

  proshield.bypass:
    description: Toggle protection bypass
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit
    default: op

  proshield.admin.tp:
    description: Teleport to claims from admin menu
    default: op

  proshield.admin.reload:
    description: Use /proshield reload
    default: op

  proshield.admin.expired.purge:
    description: Manage expired claims
    default: op

  proshield.admin.keepdrops:
    description: Toggle global 'keep items in claims' (admin GUI)
    default: op
