name: ProShield
version: 1.1.6
main: com.snazzytom.proshield.ProShield
api-version: 1.19
author: snazzytom
description: A land claim and protection plugin with GUI support.

commands:
  proshield:
    description: Main command for ProShield land claiming.
    usage: /<command> <create|remove>
    aliases: [ps, protect]

permissions:
  proshield.use:
    description: Allows use of /proshield commands
    default: true
  proshield.admin:
    description: Allows bypass of protections and admin control
    default: op
