name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.7
api-version: 1.19
author: snazzyatoms
description: A simple land protection plugin with GUI support.

commands:
  proshield:
    description: Main command for ProShield.
    usage: /proshield <claim|unclaim>
    aliases: [ps]
    permission: proshield.use

permissions:
  proshield.use:
    description: Allows using the /proshield command and GUI.
    default: true
  proshield.admin:
    description: Allows managing other players’ claims.
    default: op
