name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.0.7
api-version: 1.16
author: snazzyatoms
description: A simple plot protection plugin.
commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command>
softdepend:
  - DiscordSRV
