name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.0
api-version: 1.18
author: snazzyatoms
description: Land and plot protection plugin with GUI management and admin tools.

softdepend:
  - Vault
  - LuckPerms
  - PlaceholderAPI

commands:
  proshield:
    description: Main ProShield command
    usage: |
      /proshield
      /proshield claim
      /proshield unclaim
      /proshield info
      /proshield compass
      /proshield trust <player>
      /proshield untrust <player>
      /proshield trusted
      /proshield bypass <on|off|toggle>
      /proshield reload
      /proshield sell

permissions:
  proshield.use:
    description: Allows players to use ProShield commands and GUI
    default: true
  proshield.admin:
    description: Admin features (compass, force unclaim, teleport, bypass toggle, claim management)
    default: op
  proshield.compass:
    description: Receive/use the ProShield compass
    default: op
  proshield.bypass:
    description: Toggle protection bypass
    default: op
  proshield.unlimited:
    description: Ignore max-claims limit
    default: op
  proshield.admin.tp:
    description: Teleport to player claims via admin menu
    default: op
  proshield.admin.reload:
    description: Allows /proshield reload
    default: op
  proshield.admin.expired.purge:
    description: Allows expiring/purging claims
    default: op
