name: ProShield
main: com.proshield.ProShield
version: 1.1.4
api-version: 1.20
author: SnazzyAtoms
description: Land protection plugin for Spigot/Paper servers.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> <add|remove>
