name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.0.9
api-version: 1.20
author: snazzyatoms
description: A land and plot protection plugin.
softdepend: [DiscordSRV]

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> help
    aliases: [pshield]
