name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.9
api-version: 1.18
author: snazzyatoms
description: Land and plot protection plugin with GUI management and admin tools.

# Soft-depend so that in the future we can hook into Vault, LuckPerms, etc.
softdepend:
  - Vault
  - LuckPerms

commands:
  proshield:
    description: Main ProShield command
    usage: |
      /proshield
      /proshield claim
      /proshield unclaim
      /proshield info
      /proshield compass
      /proshield trust <player>
      /proshield untrust <player>
      /proshield trusted
      /proshield bypass <on|off|toggle>
      /proshield reload
      /proshield sell <price>   # (future economy/shop integration)

permissions:
  proshield.use:
    description: Allows players to use ProShield commands and GUI
    default: true

  proshield.admin:
    description: Grants access to admin features (admin compass, force unclaim, teleport, expired claims management)
    default: op

  proshield.compass:
    description: Allows a player to receive and use the ProShield compass
    default: op

  proshield.bypass:
    description: Allows toggling protection bypass
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit (server owners can toggle in config)
    default: false

  proshield.admin.tp:
    description: Allows teleporting to other players’ claims from the admin menu
    default: op

  proshield.reload:
    description: Allows /proshield reload (config + admin.yml)
    default: op

  proshield.admin.expired.purge:
    description: Allows purging expired claims manually
    default: op
