name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.0.5
api-version: 1.16
author: snazzyatoms
description: A plugin to manage protected plots and growth control.
commands:
  claimplot:
    description: Claim a plot of land.
    usage: /<command>
  unclaimplot:
    description: Unclaim your current plot.
    usage: /<command>
  addmember:
    description: Add a player to your plot.
    usage: /<command> <player>
  removemember:
    description: Remove a player from your plot.
    usage: /<command> <player>
softdepend:
  - DiscordSRV
