name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
api-version: 1.17
author: SnazzyAtoms
description: >
  ProShield provides claim management, plot protection, and admin tools
  including the ProShield Admin Compass for managing plots via a GUI.

commands:
  proshield:
    description: Main ProShield command with subcommands for management.
    usage: /<command> [subcommand]
    aliases: [pshield]
    permission: proshield.use

permissions:
  proshield.*:
    description: Grants access to all ProShield features.
    default: op
    children:
      proshield.use: true
      proshield.admin: true
      proshield.compass: true

  proshield.use:
    description: Allows players to use basic ProShield commands.
    default: true

  proshield.admin:
    description: Grants access to all administrative features of ProShield.
    default: op

  proshield.compass:
    description: Allows the player to use /proshield compass and receive the Admin Compass.
    default: op
