name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
author: SnazzyAtoms
description: Land and plot protection plugin for Spigot/Paper servers.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> [reload|info|help]
    permission: proshield.use

permissions:
  proshield.*:
    description: Grants access to all ProShield commands
    default: op
    children:
      proshield.use: true
      proshield.admin: true
      proshield.build: true

  proshield.use:
    description: Allows using ProShield commands (info, help, etc.)
    default: true

  proshield.admin:
    description: Allows admin-level ProShield commands (reload, reset, bypass, etc.)
    default: op

  proshield.build:
    description: Allows players to build/place/break in protected plots
    default: false
