name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
author: SnazzyAtoms
description: Land and protection plugin for Spigot/Paper servers.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> <add|remove|info|reload>
    permission: proshield.use

permissions:
  proshield.*:
    description: Grants access to all ProShield commands
    default: op
    children:
      proshield.use: true
      proshield.admin: true

  proshield.use:
    description: Allows using basic ProShield commands (claim, manage plots, etc.)
    default: true

  proshield.admin:
    description: Allows admin-level ProShield commands (reset, reload, bypass, etc.)
    default: op
