name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.8
api-version: 1.18
author: snazzyatoms
description: Land and plot protection plugin with GUI management and admin tools.

commands:
  proshield:
    description: Main ProShield command
    usage: /<command> [subcommand]

permissions:
  proshield.use:
    description: Allows players to use ProShield commands and GUI
    default: true

  proshield.admin:
    description: Grants access to admin features (admin compass, forced unclaim, etc.)
    default: op

  proshield.compass:
    description: Allows a player to receive and use the ProShield compass
    default: op

  proshield.bypass:
    description: Allows toggling protection bypass
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit
    default: op
