name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.0.8
api-version: 1.20
author: SnazzyAtoms
description: A lightweight protection plugin for Minecraft servers.

commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command>

permissions:
  proshield.use:
    description: Allows use of ProShield commands
    default: true

softdepend:
  - DiscordSRV
