# path: src/main/resources/plugin.yml
name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.4
api-version: 1.18
author: snazzyatoms
description: Land and plot protection plugin with GUI management and admin tools.
softdepend: [Vault, LuckPerms]

commands:
  proshield:
    description: Main ProShield command
    usage: |
      /proshield
      /proshield claim
      /proshield unclaim
      /proshield info
      /proshield compass
      /proshield trust <player> [role]
      /proshield untrust <player>
      /proshield trusted
      /proshield bypass <on|off|toggle>
      /proshield preview [seconds]
      /proshield transfer <player>
      /proshield purgeexpired <days> [dryrun]
      /proshield debug <on|off|toggle>
      /proshield reload

permissions:
  proshield.use:
    description: Use ProShield commands and GUI
    default: true

  proshield.admin:
    description: Admin tools (bypass, transfer, purge, preview, admin GUI)
    default: op

  proshield.compass:
    description: Receive/use the ProShield compass
    default: op

  proshield.bypass:
    description: Toggle protection bypass
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit
    default: op

  proshield.admin.tp:
    description: Teleport to claims from admin menu
    default: op

  proshield.admin.reload:
    description: Allows /proshield reload
    default: op

  proshield.admin.expired.purge:
    description: Purge expired claims (command or GUI)
    default: op

  proshield.admin.debug:
    description: Toggle debug logging
    default: op

  proshield.admin.keepdrops:
    description: Toggle claim item-drop keep/anti-despawn in admin GUI
    default: op

  # Back-compat alias for earlier typo ("keydrops"); keep both so existing perms still work
  proshield.admin.keydrops:
    description: (Alias) Toggle claim item-drop keep/anti-despawn in admin GUI
    default: op

  proshield.admin.gui:
    description: Open the ProShield Admin GUI
    default: op
