name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
api-version: 1.19
author: SnazzyAtoms
description: Advanced land protection plugin for Paper/Spigot servers.

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> [subcommand]
    permission: proshield.use

permissions:
  proshield.*:
    description: Grants access to all ProShield commands
    default: op
    children:
      proshield.use: true
      proshield.admin: true

  proshield.use:
    description: Allows using basic ProShield commands (claim, manage plots, etc.)
    default: true

  proshield.admin:
    description: Allows admin-level ProShield commands (reset, reload, bypass, etc.)
    default: op
