name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.7
api-version: 1.19
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield
description: Land/plot protection with a simple GUI and an admin compass.

commands:
  proshield:
    description: ProShield main command
    usage: /proshield <claim|unclaim>
    aliases: [ps]
    permission: proshield.use

permissions:
  proshield.use:
    description: Use basic ProShield commands and GUI
    default: true
  proshield.admin:
    description: Admin-level control (future)
    default: op
