name: ProShield
version: 1.0.6
main: com.snazzyatoms.proshield.ProShield
api-version: 1.16
author: snazzyatoms
description: A protection plugin to manage player plots with buffer zones.
softdepend: [DiscordSRV]
commands:
  proshield:
    description: Main command for ProShield
    usage: /<command>
