name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.7
api-version: 1.19
author: snazzyatoms
description: A land protection plugin with claim and unclaim support via commands and GUI.
website: https://github.com/snazzyatoms/ProShield

commands:
  proshield:
    description: Main command for ProShield
    usage: /<command> <claim|unclaim>
    aliases: [ps, protect]

permissions:
  proshield.use:
    description: Allows use of ProShield commands and GUI
    default: true
  proshield.admin:
    description: Allows admin-level control over ProShield
    default: op
