name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
api-version: '1.20'
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield
description: "All-in-one land & plot protection for Paper/Spigot"
# (rest of your plugin.yml unchanged)
