name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.0
api-version: 1.16
author: SnazzyAtoms
description: Plot protection plugin for Minecraft servers.
softdepend: [DiscordSRV]

commands:
  proshield:
    description: Base command for ProShield
    usage: /<command> claim [radius]
    aliases: [pshield]
