name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.5
api-version: 1.20
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield
description: >
  ProShield is a lightweight yet powerful land & plot protection plugin 
  for Spigot and Paper servers. Secure claims, manage trust & roles, 
  repel mobs, protect items, and provide intuitive GUIs for players and admins.

commands:
  proshield:
    description: Main ProShield command (admin + help dispatcher)
    usage: /<command> [args]
    aliases: [ps, shield]
    permission: proshield.use

  # Core Claim Commands
  claim:
    description: Claim your current chunk
    usage: /<command>
    permission: proshield.use

  unclaim:
    description: Unclaim your current chunk
    usage: /<command>
    permission: proshield.use

  info:
    description: Show info about the current claim
    usage: /<command>
    permission: proshield.use

  preview:
    description: Preview claim borders with particles
    usage: /<command>
    permission: proshield.preview

  compass:
    description: Get the ProShield compass
    usage: /<command>
    permission: proshield.compass

  flags:
    description: Open the claim flags menu
    usage: /<command>
    permission: proshield.flags

  # Trust & Roles
  trust:
    description: Trust a player with optional role
    usage: /<command> <player> [role]
    permission: proshield.use
    aliases: [addtrust]

  untrust:
    description: Remove trust from a player
    usage: /<command> <player>
    permission: proshield.use
    aliases: [removetrust]

  trusted:
    description: List trusted players in your claim
    usage: /<command>
    permission: proshield.use

  roles:
    description: Manage claim roles via GUI
    usage: /<command>
    permission: proshield.use

  transfer:
    description: Transfer claim ownership to another player
    usage: /<command> <player>
    permission: proshield.use

  # Admin
  reload:
    description: Reload ProShield configuration & messages
    usage: /<command>
    permission: proshield.admin.reload

permissions:
  # General Use
  proshield.use:
    description: Use ProShield commands & GUI
    default: true

  proshield.preview:
    description: Preview claim borders with particles
    default: true

  proshield.flags:
    description: Allow players to toggle claim flags (in their own claims)
    default: true

  # Compass & Tools
  proshield.compass:
    description: Receive/use ProShield compass
    default: op

  proshield.bypass:
    description: Toggle bypass mode
    default: op

  proshield.unlimited:
    description: Ignore max-claims limit
    default: op

  # Admin Core
  proshield.admin:
    description: Access admin tools (compass, bypass, force unclaim, purge)
    default: op

  proshield.admin.tp:
    description: Teleport to claims via admin tools
    default: op

  proshield.admin.reload:
    description: Reload ProShield config
    default: op

  proshield.admin.expired.purge:
    description: Manage expired claims
    default: op

  proshield.admin.keepitems:
    description: Toggle item-keep inside claims
    default: op

  proshield.admin.transfer:
    description: Transfer claim ownership
    default: op

  proshield.admin.debug:
    description: Toggle debug logging
    default: op

  proshield.admin.flags:
    description: Manage claim flags (PvP, explosions, fire, redstone, etc.)
    default: op

  proshield.admin.wilderness:
    description: Toggle wilderness entry messages and manage wilderness tools
    default: op
