name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.2.5
api-version: 1.20
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield
description: >
  ProShield is a lightweight yet powerful land & plot protection plugin 
  for Spigot and Paper servers. Secure claims, manage trust & roles, 
  repel mobs, protect items, and provide intuitive GUIs for players and admins.

commands:
  proshield:
    description: Root ProShield command (admin + utility dispatcher)
    usage: /<command> [reload|debug|help]
    aliases: [ps, shield]
    permission: proshield.use

  claim:
    description: Claim your current chunk
    usage: /<command>
    permission: proshield.use

  unclaim:
    description: Unclaim your current chunk
    usage: /<command>
    permission: proshield.use

  trust:
    description: Trust a player with optional role
    usage: /<command> <player> [role]
    permission: proshield.use
    aliases: [addtrust]

  untrust:
    description: Remove trust from a player
    usage: /<command> <player>
    permission: proshield.use
    aliases: [removetrust]

  roles:
    description: Manage claim roles via GUI
    usage: /<command>
    permission: proshield.use

  transfer:
    description: Transfer claim ownership to another player
    usage: /<command> <player>
    permission: proshield.use

permissions:
  # General Use
  proshield.use:
    description: Use ProShield commands & GUI
    default: true

  proshield.flags:
    description: Allow players to toggle claim flags (in their own claims)
    default: true

  proshield.unlimited:
    description: Ignore max-claims limit
    default: op

  # Admin Core
  proshield.admin:
    description: Access admin tools (force unclaim, purge, admin menu)
    default: op

  proshield.admin.reload:
    description: Reload ProShield config
    default: op
