name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.0.6
api-version: 1.16
author: YourName
description: A flexible land/plot protection system with GUI and optional economy/Discord integration.
commands:
  proshield:
    description: Main command for ProShield.
    usage: /<command>
softdepend: [DiscordSRV]
