name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.1
api-version: 1.20
author: snazzyatoms
description: Plot protection plugin with ProShield system.

commands:
  proshield:
    description: Main command for ProShield
    usage: /proshield
