name: ProShield
main: com.snazzyatoms.proshield.ProShield
version: 1.1.6
api-version: 1.18
author: snazzyatoms
website: https://github.com/snazzyatoms/ProShield
description: All-in-one land and plot protection for Paper/Spigot

commands:
  proshield:
    description: Main ProShield command
    usage: /<command>
    aliases: [ps, shield]
    permission: proshield.use

permissions:
  proshield.use:
    description: Allows basic ProShield commands
    default: true
  proshield.admin:
    description: Allows admin-only features (force unclaim, reload, etc.)
    default: op
